"""add land_parcel and soil_sample tables

Revision ID: 6806bc6ab322
Revises: a3d4ecb302fd
Create Date: 2025-10-29 12:27:01.778037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6806bc6ab322'
down_revision: Union[str, Sequence[str], None] = 'a3d4ecb302fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_parcel',
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('tehsil', sa.String(), nullable=True),
    sa.Column('ri_circle', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('survey_no', sa.String(), nullable=True),
    sa.Column('khata_no', sa.String(), nullable=True),
    sa.Column('plot_no', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.PrimaryKeyConstraint('parcel_id')
    )
    op.create_index(op.f('ix_land_parcel_parcel_id'), 'land_parcel', ['parcel_id'], unique=False)
    op.create_table('soil_sample',
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=True),
    sa.Column('sample_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('test_result_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sample_depth_cm', sa.Integer(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.Column('zinc', sa.Float(), nullable=True),
    sa.Column('copper', sa.Float(), nullable=True),
    sa.Column('boron', sa.Float(), nullable=True),
    sa.Column('sulfur', sa.Float(), nullable=True),
    sa.Column('iron', sa.Float(), nullable=True),
    sa.Column('manganese', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcel.parcel_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_index(op.f('ix_soil_sample_sample_id'), 'soil_sample', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soil_sample_sample_id'), table_name='soil_sample')
    op.drop_table('soil_sample')
    op.drop_index(op.f('ix_land_parcel_parcel_id'), table_name='land_parcel')
    op.drop_table('land_parcel')
    # ### end Alembic commands ###
