"""add users table

Revision ID: a3d4ecb302fd
Revises: 
Create Date: 2025-10-28 13:21:24.279517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d4ecb302fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sahayak',
    sa.Column('sahayak_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('aadhaar_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('gender_category', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('is_profile_completed', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('sahayak_id')
    )
    op.create_index(op.f('ix_sahayak_phone_number'), 'sahayak', ['phone_number'], unique=True)
    op.create_index(op.f('ix_sahayak_sahayak_id'), 'sahayak', ['sahayak_id'], unique=False)
    op.create_table('farmer',
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('aadhaar_number', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('gender_category', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sahayak_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sahayak_id'], ['sahayak.sahayak_id'], ),
    sa.PrimaryKeyConstraint('farmer_id')
    )
    op.create_index(op.f('ix_farmer_farmer_id'), 'farmer', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_phone_number'), 'farmer', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_phone_number'), table_name='farmer')
    op.drop_index(op.f('ix_farmer_farmer_id'), table_name='farmer')
    op.drop_table('farmer')
    op.drop_index(op.f('ix_sahayak_sahayak_id'), table_name='sahayak')
    op.drop_index(op.f('ix_sahayak_phone_number'), table_name='sahayak')
    op.drop_table('sahayak')
    # ### end Alembic commands ###
