"""

Revision ID: d3ac9c9a7fdb
Revises: d9f682afd8da
Create Date: 2025-10-23 05:28:54.349795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ac9c9a7fdb'
down_revision: Union[str, Sequence[str], None] = 'd9f682afd8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('aadhaar_number', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('gender_category', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_id'), 'farmer', ['id'], unique=False)
    op.create_index(op.f('ix_farmer_phone_number'), 'farmer', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_phone_number'), table_name='farmer')
    op.drop_index(op.f('ix_farmer_id'), table_name='farmer')
    op.drop_table('farmer')
    # ### end Alembic commands ###
