"""add sample_code to soil_sample

Revision ID: d64d5bfa6473
Revises: 6806bc6ab322
Create Date: 2025-10-29 13:41:51.727533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64d5bfa6473'
down_revision: Union[str, Sequence[str], None] = '6806bc6ab322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_parcel', sa.Column('survey_number', sa.String(), nullable=True))
    op.create_unique_constraint('uq_farmer_survey', 'land_parcel', ['farmer_id', 'survey_number'])
    op.drop_column('land_parcel', 'survey_no')
    op.add_column('soil_sample', sa.Column('sample_code', sa.String(), nullable=False))
    op.create_unique_constraint('uq_parcel_sample_code', 'soil_sample', ['parcel_id', 'sample_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_parcel_sample_code', 'soil_sample', type_='unique')
    op.drop_column('soil_sample', 'sample_code')
    op.add_column('land_parcel', sa.Column('survey_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_farmer_survey', 'land_parcel', type_='unique')
    op.drop_column('land_parcel', 'survey_number')
    # ### end Alembic commands ###
