"""add users

Revision ID: d75b2fe95a5b
Revises: 842a7abc5756
Create Date: 2025-10-30 13:58:45.020939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75b2fe95a5b'
down_revision: Union[str, Sequence[str], None] = '842a7abc5756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_parcel', sa.Column('survey_no', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_farmer_survey'), 'land_parcel', type_='unique')
    op.drop_column('land_parcel', 'survey_number')
    op.drop_constraint(op.f('uq_parcel_sample_code'), 'soil_sample', type_='unique')
    op.drop_column('soil_sample', 'sample_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil_sample', sa.Column('sample_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_parcel_sample_code'), 'soil_sample', ['parcel_id', 'sample_code'], postgresql_nulls_not_distinct=False)
    op.add_column('land_parcel', sa.Column('survey_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_farmer_survey'), 'land_parcel', ['farmer_id', 'survey_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('land_parcel', 'survey_no')
    # ### end Alembic commands ###
